# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimPel.ui'
#
# Created: Fri Dec  9 14:12:04 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SimPel2016(object):
    def setupUi(self, SimPel2016):
        SimPel2016.setObjectName(_fromUtf8("SimPel2016"))
        SimPel2016.resize(974, 713)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        SimPel2016.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        SimPel2016.setFont(font)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("SimPel"))
        SimPel2016.setWindowIcon(icon)
        SimPel2016.setAnimated(True)
        SimPel2016.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(SimPel2016)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Startbutton = QtGui.QPushButton(self.centralwidget)
        self.Startbutton.setGeometry(QtCore.QRect(620, 630, 91, 21))
        self.Startbutton.setAutoFillBackground(False)
        self.Startbutton.setObjectName(_fromUtf8("Startbutton"))
        self.Savebutton = QtGui.QPushButton(self.centralwidget)
        self.Savebutton.setGeometry(QtCore.QRect(730, 630, 81, 21))
        self.Savebutton.setAutoFillBackground(False)
        self.Savebutton.setObjectName(_fromUtf8("Savebutton"))
        self.widgetplot = QtGui.QWidget(self.centralwidget)
        self.widgetplot.setEnabled(True)
        self.widgetplot.setGeometry(QtCore.QRect(0, -3, 521, 411))
        self.widgetplot.setObjectName(_fromUtf8("widgetplot"))
        self.Closebutton = QtGui.QPushButton(self.centralwidget)
        self.Closebutton.setGeometry(QtCore.QRect(830, 630, 71, 20))
        self.Closebutton.setAutoFillBackground(False)
        self.Closebutton.setObjectName(_fromUtf8("Closebutton"))
        self.panPELDORTT = QtGui.QPushButton(self.centralwidget)
        self.panPELDORTT.setGeometry(QtCore.QRect(240, 410, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.panPELDORTT.setFont(font)
        self.panPELDORTT.setObjectName(_fromUtf8("panPELDORTT"))
        self.zoomButtonPeldorTT = QtGui.QPushButton(self.centralwidget)
        self.zoomButtonPeldorTT.setGeometry(QtCore.QRect(130, 410, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zoomButtonPeldorTT.setFont(font)
        self.zoomButtonPeldorTT.setObjectName(_fromUtf8("zoomButtonPeldorTT"))
        self.Distancedistrwindow = QtGui.QWidget(self.centralwidget)
        self.Distancedistrwindow.setGeometry(QtCore.QRect(260, 420, 261, 251))
        self.Distancedistrwindow.setObjectName(_fromUtf8("Distancedistrwindow"))
        self.FTwindow = QtGui.QWidget(self.centralwidget)
        self.FTwindow.setGeometry(QtCore.QRect(10, 420, 251, 251))
        self.FTwindow.setObjectName(_fromUtf8("FTwindow"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(540, 20, 191, 272))
        self.frame.setStyleSheet(_fromUtf8("background-color:rgb(0, 196, 255)"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.Coeff5edit = QtGui.QLineEdit(self.frame)
        self.Coeff5edit.setGeometry(QtCore.QRect(125, 230, 31, 27))
        self.Coeff5edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Coeff5edit.setObjectName(_fromUtf8("Coeff5edit"))
        self.Coeff3edit = QtGui.QLineEdit(self.frame)
        self.Coeff3edit.setGeometry(QtCore.QRect(125, 150, 31, 27))
        self.Coeff3edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Coeff3edit.setObjectName(_fromUtf8("Coeff3edit"))
        self.labeldistances_2 = QtGui.QLabel(self.frame)
        self.labeldistances_2.setGeometry(QtCore.QRect(55, 76, 31, 16))
        self.labeldistances_2.setObjectName(_fromUtf8("labeldistances_2"))
        self.labeldistances_19 = QtGui.QLabel(self.frame)
        self.labeldistances_19.setGeometry(QtCore.QRect(55, 236, 31, 16))
        self.labeldistances_19.setObjectName(_fromUtf8("labeldistances_19"))
        self.Distance4edit = QtGui.QLineEdit(self.frame)
        self.Distance4edit.setGeometry(QtCore.QRect(20, 190, 31, 27))
        self.Distance4edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Distance4edit.setObjectName(_fromUtf8("Distance4edit"))
        self.Coeff2edit = QtGui.QLineEdit(self.frame)
        self.Coeff2edit.setGeometry(QtCore.QRect(125, 110, 31, 27))
        self.Coeff2edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Coeff2edit.setObjectName(_fromUtf8("Coeff2edit"))
        self.labeldistances_29 = QtGui.QLabel(self.frame)
        self.labeldistances_29.setGeometry(QtCore.QRect(25, 15, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_29.setFont(font)
        self.labeldistances_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labeldistances_29.setObjectName(_fromUtf8("labeldistances_29"))
        self.Distance3edit = QtGui.QLineEdit(self.frame)
        self.Distance3edit.setGeometry(QtCore.QRect(20, 150, 31, 27))
        self.Distance3edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Distance3edit.setObjectName(_fromUtf8("Distance3edit"))
        self.Coeff4edit = QtGui.QLineEdit(self.frame)
        self.Coeff4edit.setGeometry(QtCore.QRect(125, 190, 31, 27))
        self.Coeff4edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Coeff4edit.setObjectName(_fromUtf8("Coeff4edit"))
        self.labeldistances = QtGui.QLabel(self.frame)
        self.labeldistances.setGeometry(QtCore.QRect(20, 50, 71, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labeldistances.setFont(font)
        self.labeldistances.setObjectName(_fromUtf8("labeldistances"))
        self.labeldistances_4 = QtGui.QLabel(self.frame)
        self.labeldistances_4.setGeometry(QtCore.QRect(55, 196, 31, 16))
        self.labeldistances_4.setObjectName(_fromUtf8("labeldistances_4"))
        self.Distance5edit = QtGui.QLineEdit(self.frame)
        self.Distance5edit.setGeometry(QtCore.QRect(20, 230, 31, 27))
        self.Distance5edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Distance5edit.setObjectName(_fromUtf8("Distance5edit"))
        self.Distance2edit = QtGui.QLineEdit(self.frame)
        self.Distance2edit.setGeometry(QtCore.QRect(20, 110, 31, 27))
        self.Distance2edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Distance2edit.setObjectName(_fromUtf8("Distance2edit"))
        self.labeldistances_3 = QtGui.QLabel(self.frame)
        self.labeldistances_3.setGeometry(QtCore.QRect(55, 116, 31, 16))
        self.labeldistances_3.setObjectName(_fromUtf8("labeldistances_3"))
        self.labeldistances_5 = QtGui.QLabel(self.frame)
        self.labeldistances_5.setGeometry(QtCore.QRect(55, 156, 31, 16))
        self.labeldistances_5.setObjectName(_fromUtf8("labeldistances_5"))
        self.Coeff1edit = QtGui.QLineEdit(self.frame)
        self.Coeff1edit.setGeometry(QtCore.QRect(125, 70, 31, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Coeff1edit.setPalette(palette)
        self.Coeff1edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Coeff1edit.setObjectName(_fromUtf8("Coeff1edit"))
        self.Distance1edit = QtGui.QLineEdit(self.frame)
        self.Distance1edit.setGeometry(QtCore.QRect(20, 70, 31, 27))
        self.Distance1edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Distance1edit.setObjectName(_fromUtf8("Distance1edit"))
        self.labeldistances_7 = QtGui.QLabel(self.frame)
        self.labeldistances_7.setGeometry(QtCore.QRect(100, 50, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labeldistances_7.setFont(font)
        self.labeldistances_7.setObjectName(_fromUtf8("labeldistances_7"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(540, 310, 231, 241))
        self.frame_2.setStyleSheet(_fromUtf8("background-color:rgb(0, 196, 255)"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.labeldistances_13 = QtGui.QLabel(self.frame_2)
        self.labeldistances_13.setGeometry(QtCore.QRect(130, 50, 81, 17))
        self.labeldistances_13.setObjectName(_fromUtf8("labeldistances_13"))
        self.labeldistances_18 = QtGui.QLabel(self.frame_2)
        self.labeldistances_18.setGeometry(QtCore.QRect(185, 146, 31, 16))
        self.labeldistances_18.setObjectName(_fromUtf8("labeldistances_18"))
        self.Moddepthedit = QtGui.QLineEdit(self.frame_2)
        self.Moddepthedit.setGeometry(QtCore.QRect(150, 70, 31, 27))
        self.Moddepthedit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Moddepthedit.setObjectName(_fromUtf8("Moddepthedit"))
        self.Timescaleedit = QtGui.QLineEdit(self.frame_2)
        self.Timescaleedit.setGeometry(QtCore.QRect(20, 70, 51, 27))
        self.Timescaleedit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Timescaleedit.setObjectName(_fromUtf8("Timescaleedit"))
        self.labeldistances_17 = QtGui.QLabel(self.frame_2)
        self.labeldistances_17.setGeometry(QtCore.QRect(20, 190, 101, 17))
        self.labeldistances_17.setObjectName(_fromUtf8("labeldistances_17"))
        self.labeldistances_9 = QtGui.QLabel(self.frame_2)
        self.labeldistances_9.setGeometry(QtCore.QRect(75, 76, 31, 16))
        self.labeldistances_9.setObjectName(_fromUtf8("labeldistances_9"))
        self.labeldistances_10 = QtGui.QLabel(self.frame_2)
        self.labeldistances_10.setGeometry(QtCore.QRect(20, 50, 71, 17))
        self.labeldistances_10.setObjectName(_fromUtf8("labeldistances_10"))
        self.Timescalebox = QtGui.QSpinBox(self.frame_2)
        self.Timescalebox.setEnabled(True)
        self.Timescalebox.setGeometry(QtCore.QRect(20, 140, 51, 27))
        self.Timescalebox.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Timescalebox.setReadOnly(False)
        self.Timescalebox.setMinimum(4)
        self.Timescalebox.setMaximum(32)
        self.Timescalebox.setSingleStep(4)
        self.Timescalebox.setProperty("value", 8)
        self.Timescalebox.setObjectName(_fromUtf8("Timescalebox"))
        self.Sigmaedit = QtGui.QLineEdit(self.frame_2)
        self.Sigmaedit.setGeometry(QtCore.QRect(140, 140, 41, 27))
        self.Sigmaedit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Sigmaedit.setObjectName(_fromUtf8("Sigmaedit"))
        self.EnableNoiseButton = QtGui.QRadioButton(self.frame_2)
        self.EnableNoiseButton.setGeometry(QtCore.QRect(100, 216, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.EnableNoiseButton.setFont(font)
        self.EnableNoiseButton.setCheckable(True)
        self.EnableNoiseButton.setChecked(False)
        self.EnableNoiseButton.setAutoExclusive(False)
        self.EnableNoiseButton.setObjectName(_fromUtf8("EnableNoiseButton"))
        self.labeldistances_11 = QtGui.QLabel(self.frame_2)
        self.labeldistances_11.setGeometry(QtCore.QRect(56, 15, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_11.setFont(font)
        self.labeldistances_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labeldistances_11.setObjectName(_fromUtf8("labeldistances_11"))
        self.labeldistances_12 = QtGui.QLabel(self.frame_2)
        self.labeldistances_12.setGeometry(QtCore.QRect(130, 120, 101, 17))
        self.labeldistances_12.setObjectName(_fromUtf8("labeldistances_12"))
        self.labeldistances_8 = QtGui.QLabel(self.frame_2)
        self.labeldistances_8.setGeometry(QtCore.QRect(20, 120, 71, 17))
        self.labeldistances_8.setObjectName(_fromUtf8("labeldistances_8"))
        self.SNR_edit = QtGui.QLineEdit(self.frame_2)
        self.SNR_edit.setGeometry(QtCore.QRect(20, 210, 41, 27))
        self.SNR_edit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.SNR_edit.setObjectName(_fromUtf8("SNR_edit"))
        self.labeldistances_6 = QtGui.QLabel(self.frame_2)
        self.labeldistances_6.setGeometry(QtCore.QRect(75, 146, 31, 16))
        self.labeldistances_6.setObjectName(_fromUtf8("labeldistances_6"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(780, 310, 181, 241))
        self.frame_3.setStyleSheet(_fromUtf8("background-color:rgb(0, 196, 255)"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.EnableBgButton = QtGui.QRadioButton(self.frame_3)
        self.EnableBgButton.setGeometry(QtCore.QRect(20, 210, 161, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.EnableBgButton.setFont(font)
        self.EnableBgButton.setCheckable(True)
        self.EnableBgButton.setChecked(True)
        self.EnableBgButton.setAutoExclusive(False)
        self.EnableBgButton.setObjectName(_fromUtf8("EnableBgButton"))
        self.labeldistances_16 = QtGui.QLabel(self.frame_3)
        self.labeldistances_16.setGeometry(QtCore.QRect(20, 50, 101, 17))
        self.labeldistances_16.setObjectName(_fromUtf8("labeldistances_16"))
        self.BgDimbox = QtGui.QSpinBox(self.frame_3)
        self.BgDimbox.setEnabled(True)
        self.BgDimbox.setGeometry(QtCore.QRect(20, 140, 51, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.BgDimbox.setPalette(palette)
        self.BgDimbox.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.BgDimbox.setReadOnly(False)
        self.BgDimbox.setMinimum(1)
        self.BgDimbox.setMaximum(3)
        self.BgDimbox.setSingleStep(1)
        self.BgDimbox.setProperty("value", 3)
        self.BgDimbox.setObjectName(_fromUtf8("BgDimbox"))
        self.Bgdecayedit = QtGui.QLineEdit(self.frame_3)
        self.Bgdecayedit.setGeometry(QtCore.QRect(20, 70, 41, 27))
        self.Bgdecayedit.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.Bgdecayedit.setObjectName(_fromUtf8("Bgdecayedit"))
        self.labeldistances_15 = QtGui.QLabel(self.frame_3)
        self.labeldistances_15.setGeometry(QtCore.QRect(50, 15, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_15.setFont(font)
        self.labeldistances_15.setObjectName(_fromUtf8("labeldistances_15"))
        self.labeldistances_14 = QtGui.QLabel(self.frame_3)
        self.labeldistances_14.setGeometry(QtCore.QRect(20, 120, 101, 17))
        self.labeldistances_14.setObjectName(_fromUtf8("labeldistances_14"))
        self.ShowBGButton = QtGui.QRadioButton(self.frame_3)
        self.ShowBGButton.setGeometry(QtCore.QRect(20, 190, 161, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ShowBGButton.setFont(font)
        self.ShowBGButton.setAutoExclusive(False)
        self.ShowBGButton.setObjectName(_fromUtf8("ShowBGButton"))
        self.JarasprogressBar = QtGui.QProgressBar(self.centralwidget)
        self.JarasprogressBar.setGeometry(QtCore.QRect(550, 580, 231, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 196, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.JarasprogressBar.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.JarasprogressBar.setFont(font)
        self.JarasprogressBar.setStyleSheet(_fromUtf8("background-color:rgb(0, 196, 255)"))
        self.JarasprogressBar.setMaximum(100)
        self.JarasprogressBar.setProperty("value", 0)
        self.JarasprogressBar.setObjectName(_fromUtf8("JarasprogressBar"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(740, 20, 221, 271))
        self.frame_4.setStyleSheet(_fromUtf8("background-color:rgb(0, 196, 255)"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.labeldistances_30 = QtGui.QLabel(self.frame_4)
        self.labeldistances_30.setGeometry(QtCore.QRect(38, 15, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_30.setFont(font)
        self.labeldistances_30.setObjectName(_fromUtf8("labeldistances_30"))
        self.ButtonTrapezoidal = QtGui.QRadioButton(self.frame_4)
        self.ButtonTrapezoidal.setGeometry(QtCore.QRect(9, 60, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ButtonTrapezoidal.setFont(font)
        self.ButtonTrapezoidal.setChecked(True)
        self.ButtonTrapezoidal.setObjectName(_fromUtf8("ButtonTrapezoidal"))
        self.ButtonAdaptive = QtGui.QRadioButton(self.frame_4)
        self.ButtonAdaptive.setGeometry(QtCore.QRect(9, 80, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ButtonAdaptive.setFont(font)
        self.ButtonAdaptive.setObjectName(_fromUtf8("ButtonAdaptive"))
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(16, 41, 201, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.Checkbox_superadaptive = QtGui.QCheckBox(self.frame_4)
        self.Checkbox_superadaptive.setGeometry(QtCore.QRect(9, 100, 211, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Checkbox_superadaptive.setFont(font)
        self.Checkbox_superadaptive.setObjectName(_fromUtf8("Checkbox_superadaptive"))
        self.ButtonFullyAdaptive = QtGui.QRadioButton(self.frame_4)
        self.ButtonFullyAdaptive.setGeometry(QtCore.QRect(9, 145, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ButtonFullyAdaptive.setFont(font)
        self.ButtonFullyAdaptive.setObjectName(_fromUtf8("ButtonFullyAdaptive"))
        self.label_2 = QtGui.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(17, 127, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.DetachButton = QtGui.QPushButton(self.centralwidget)
        self.DetachButton.setGeometry(QtCore.QRect(347, 410, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DetachButton.setFont(font)
        self.DetachButton.setObjectName(_fromUtf8("DetachButton"))
        SimPel2016.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SimPel2016)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        SimPel2016.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SimPel2016)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SimPel2016.setStatusBar(self.statusbar)

        self.retranslateUi(SimPel2016)
        QtCore.QMetaObject.connectSlotsByName(SimPel2016)

    def retranslateUi(self, SimPel2016):
        SimPel2016.setWindowTitle(_translate("SimPel2016", "SimPel2016", None))
        self.Startbutton.setText(_translate("SimPel2016", "Start", None))
        self.Savebutton.setText(_translate("SimPel2016", "Save", None))
        self.Closebutton.setText(_translate("SimPel2016", "Exit", None))
        self.panPELDORTT.setText(_translate("SimPel2016", "Pan", None))
        self.zoomButtonPeldorTT.setText(_translate("SimPel2016", "Zoom", None))
        self.Coeff5edit.setText(_translate("SimPel2016", "0.0", None))
        self.Coeff3edit.setText(_translate("SimPel2016", "0.0", None))
        self.labeldistances_2.setText(_translate("SimPel2016", "nm", None))
        self.labeldistances_19.setText(_translate("SimPel2016", "nm", None))
        self.Distance4edit.setText(_translate("SimPel2016", "2.0", None))
        self.Coeff2edit.setText(_translate("SimPel2016", "0.0", None))
        self.labeldistances_29.setText(_translate("SimPel2016", "Distance Settings", None))
        self.Distance3edit.setText(_translate("SimPel2016", "2.0", None))
        self.Coeff4edit.setText(_translate("SimPel2016", "0.0", None))
        self.labeldistances.setText(_translate("SimPel2016", "Distances", None))
        self.labeldistances_4.setText(_translate("SimPel2016", "nm", None))
        self.Distance5edit.setText(_translate("SimPel2016", "2.0", None))
        self.Distance2edit.setText(_translate("SimPel2016", "2.0", None))
        self.labeldistances_3.setText(_translate("SimPel2016", "nm", None))
        self.labeldistances_5.setText(_translate("SimPel2016", "nm", None))
        self.Coeff1edit.setText(_translate("SimPel2016", "1.0", None))
        self.Distance1edit.setText(_translate("SimPel2016", "2.0", None))
        self.labeldistances_7.setText(_translate("SimPel2016", "Coefficients", None))
        self.labeldistances_13.setText(_translate("SimPel2016", "Mod. Depth", None))
        self.labeldistances_18.setText(_translate("SimPel2016", "nm", None))
        self.Moddepthedit.setText(_translate("SimPel2016", "0.2", None))
        self.Timescaleedit.setText(_translate("SimPel2016", "1500", None))
        self.labeldistances_17.setText(_translate("SimPel2016", "Signal-to-noise", None))
        self.labeldistances_9.setText(_translate("SimPel2016", "ns", None))
        self.labeldistances_10.setText(_translate("SimPel2016", "Time scale", None))
        self.Sigmaedit.setText(_translate("SimPel2016", "0.1", None))
        self.EnableNoiseButton.setText(_translate("SimPel2016", "Enable Noise", None))
        self.labeldistances_11.setText(_translate("SimPel2016", "Other Settings", None))
        self.labeldistances_12.setText(_translate("SimPel2016", "Standard Dev.", None))
        self.labeldistances_8.setText(_translate("SimPel2016", "Stepsize", None))
        self.SNR_edit.setText(_translate("SimPel2016", "20.0", None))
        self.labeldistances_6.setText(_translate("SimPel2016", "ns", None))
        self.EnableBgButton.setText(_translate("SimPel2016", "Enable Bg. ", None))
        self.labeldistances_16.setText(_translate("SimPel2016", "Bg. Decay", None))
        self.Bgdecayedit.setText(_translate("SimPel2016", "1.0", None))
        self.labeldistances_15.setText(_translate("SimPel2016", "Background", None))
        self.labeldistances_14.setText(_translate("SimPel2016", "Bg. Dimension", None))
        self.ShowBGButton.setText(_translate("SimPel2016", "Show Bg. Function", None))
        self.labeldistances_30.setText(_translate("SimPel2016", "Advanced Settings", None))
        self.ButtonTrapezoidal.setText(_translate("SimPel2016", "Trapezoidal Integration", None))
        self.ButtonAdaptive.setText(_translate("SimPel2016", "Adaptive Integration", None))
        self.label.setText(_translate("SimPel2016", "Standard Integrations methods", None))
        self.Checkbox_superadaptive.setText(_translate("SimPel2016", "Enable highly adaptive Gaussians", None))
        self.ButtonFullyAdaptive.setText(_translate("SimPel2016", "Fully double Integration", None))
        self.label_2.setText(_translate("SimPel2016", "High accuracy Integration ", None))
        self.DetachButton.setText(_translate("SimPel2016", "Detach", None))

