# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimPel_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimPel2018(object):
    def setupUi(self, SimPel2018):
        SimPel2018.setObjectName("SimPel2018")
        SimPel2018.resize(862, 589)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimPel2018.sizePolicy().hasHeightForWidth())
        SimPel2018.setSizePolicy(sizePolicy)
        SimPel2018.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        SimPel2018.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        SimPel2018.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("SimPel_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SimPel2018.setWindowIcon(icon)
        SimPel2018.setStyleSheet("background-color: rgb(240, 255, 200);")
        SimPel2018.setAnimated(True)
        SimPel2018.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(SimPel2018)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetplot = QtWidgets.QWidget(self.centralwidget)
        self.widgetplot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetplot.sizePolicy().hasHeightForWidth())
        self.widgetplot.setSizePolicy(sizePolicy)
        self.widgetplot.setMinimumSize(QtCore.QSize(360, 230))
        self.widgetplot.setMaximumSize(QtCore.QSize(900, 600))
        self.widgetplot.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetplot.setObjectName("widgetplot")
        self.gridLayout.addWidget(self.widgetplot, 0, 0, 1, 4)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(230, 235))
        self.frame.setMaximumSize(QtCore.QSize(230, 235))
        self.frame.setStyleSheet("background-color: rgb(229, 255, 192);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.Coeff5edit = QtWidgets.QLineEdit(self.frame)
        self.Coeff5edit.setGeometry(QtCore.QRect(90, 205, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Coeff5edit.setFont(font)
        self.Coeff5edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Coeff5edit.setObjectName("Coeff5edit")
        self.Coeff3edit = QtWidgets.QLineEdit(self.frame)
        self.Coeff3edit.setGeometry(QtCore.QRect(90, 135, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Coeff3edit.setFont(font)
        self.Coeff3edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Coeff3edit.setObjectName("Coeff3edit")
        self.labeldistances_2 = QtWidgets.QLabel(self.frame)
        self.labeldistances_2.setGeometry(QtCore.QRect(50, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_2.setFont(font)
        self.labeldistances_2.setObjectName("labeldistances_2")
        self.labeldistances_19 = QtWidgets.QLabel(self.frame)
        self.labeldistances_19.setGeometry(QtCore.QRect(50, 210, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_19.setFont(font)
        self.labeldistances_19.setObjectName("labeldistances_19")
        self.Distance4edit = QtWidgets.QLineEdit(self.frame)
        self.Distance4edit.setGeometry(QtCore.QRect(10, 170, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Distance4edit.setFont(font)
        self.Distance4edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Distance4edit.setObjectName("Distance4edit")
        self.Coeff2edit = QtWidgets.QLineEdit(self.frame)
        self.Coeff2edit.setGeometry(QtCore.QRect(90, 100, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Coeff2edit.setFont(font)
        self.Coeff2edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Coeff2edit.setObjectName("Coeff2edit")
        self.labeldistances_29 = QtWidgets.QLabel(self.frame)
        self.labeldistances_29.setGeometry(QtCore.QRect(40, 10, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_29.setFont(font)
        self.labeldistances_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labeldistances_29.setObjectName("labeldistances_29")
        self.Distance3edit = QtWidgets.QLineEdit(self.frame)
        self.Distance3edit.setGeometry(QtCore.QRect(10, 135, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Distance3edit.setFont(font)
        self.Distance3edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Distance3edit.setObjectName("Distance3edit")
        self.Coeff4edit = QtWidgets.QLineEdit(self.frame)
        self.Coeff4edit.setGeometry(QtCore.QRect(90, 170, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Coeff4edit.setFont(font)
        self.Coeff4edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Coeff4edit.setObjectName("Coeff4edit")
        self.labeldistances = QtWidgets.QLabel(self.frame)
        self.labeldistances.setGeometry(QtCore.QRect(10, 41, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labeldistances.setFont(font)
        self.labeldistances.setObjectName("labeldistances")
        self.labeldistances_4 = QtWidgets.QLabel(self.frame)
        self.labeldistances_4.setGeometry(QtCore.QRect(50, 175, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_4.setFont(font)
        self.labeldistances_4.setObjectName("labeldistances_4")
        self.Distance5edit = QtWidgets.QLineEdit(self.frame)
        self.Distance5edit.setGeometry(QtCore.QRect(10, 205, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Distance5edit.setFont(font)
        self.Distance5edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Distance5edit.setObjectName("Distance5edit")
        self.Distance2edit = QtWidgets.QLineEdit(self.frame)
        self.Distance2edit.setGeometry(QtCore.QRect(10, 100, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Distance2edit.setFont(font)
        self.Distance2edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Distance2edit.setObjectName("Distance2edit")
        self.labeldistances_3 = QtWidgets.QLabel(self.frame)
        self.labeldistances_3.setGeometry(QtCore.QRect(50, 104, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_3.setFont(font)
        self.labeldistances_3.setObjectName("labeldistances_3")
        self.labeldistances_5 = QtWidgets.QLabel(self.frame)
        self.labeldistances_5.setGeometry(QtCore.QRect(50, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_5.setFont(font)
        self.labeldistances_5.setObjectName("labeldistances_5")
        self.Coeff1edit = QtWidgets.QLineEdit(self.frame)
        self.Coeff1edit.setGeometry(QtCore.QRect(90, 64, 35, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Coeff1edit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Coeff1edit.setFont(font)
        self.Coeff1edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Coeff1edit.setObjectName("Coeff1edit")
        self.Distance1edit = QtWidgets.QLineEdit(self.frame)
        self.Distance1edit.setGeometry(QtCore.QRect(10, 64, 35, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Distance1edit.setFont(font)
        self.Distance1edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Distance1edit.setObjectName("Distance1edit")
        self.labeldistances_7 = QtWidgets.QLabel(self.frame)
        self.labeldistances_7.setGeometry(QtCore.QRect(90, 41, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labeldistances_7.setFont(font)
        self.labeldistances_7.setObjectName("labeldistances_7")
        self.labeldistances_20 = QtWidgets.QLabel(self.frame)
        self.labeldistances_20.setGeometry(QtCore.QRect(145, 41, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labeldistances_20.setFont(font)
        self.labeldistances_20.setObjectName("labeldistances_20")
        self.Standard1 = QtWidgets.QLineEdit(self.frame)
        self.Standard1.setGeometry(QtCore.QRect(150, 64, 35, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Standard1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Standard1.setFont(font)
        self.Standard1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Standard1.setObjectName("Standard1")
        self.Standard2 = QtWidgets.QLineEdit(self.frame)
        self.Standard2.setGeometry(QtCore.QRect(150, 100, 35, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Standard2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Standard2.setFont(font)
        self.Standard2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Standard2.setObjectName("Standard2")
        self.Standard3 = QtWidgets.QLineEdit(self.frame)
        self.Standard3.setGeometry(QtCore.QRect(150, 135, 35, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Standard3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Standard3.setFont(font)
        self.Standard3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Standard3.setObjectName("Standard3")
        self.Standard4 = QtWidgets.QLineEdit(self.frame)
        self.Standard4.setGeometry(QtCore.QRect(150, 170, 35, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Standard4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Standard4.setFont(font)
        self.Standard4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Standard4.setObjectName("Standard4")
        self.Standard5 = QtWidgets.QLineEdit(self.frame)
        self.Standard5.setGeometry(QtCore.QRect(150, 205, 35, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Standard5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Standard5.setFont(font)
        self.Standard5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Standard5.setObjectName("Standard5")
        self.labeldistances_22 = QtWidgets.QLabel(self.frame)
        self.labeldistances_22.setGeometry(QtCore.QRect(190, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_22.setFont(font)
        self.labeldistances_22.setObjectName("labeldistances_22")
        self.labeldistances_23 = QtWidgets.QLabel(self.frame)
        self.labeldistances_23.setGeometry(QtCore.QRect(190, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_23.setFont(font)
        self.labeldistances_23.setObjectName("labeldistances_23")
        self.labeldistances_24 = QtWidgets.QLabel(self.frame)
        self.labeldistances_24.setGeometry(QtCore.QRect(190, 210, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_24.setFont(font)
        self.labeldistances_24.setObjectName("labeldistances_24")
        self.labeldistances_25 = QtWidgets.QLabel(self.frame)
        self.labeldistances_25.setGeometry(QtCore.QRect(190, 104, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_25.setFont(font)
        self.labeldistances_25.setObjectName("labeldistances_25")
        self.labeldistances_26 = QtWidgets.QLabel(self.frame)
        self.labeldistances_26.setGeometry(QtCore.QRect(190, 175, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_26.setFont(font)
        self.labeldistances_26.setObjectName("labeldistances_26")
        self.gridLayout.addWidget(self.frame, 0, 4, 1, 3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(210, 235))
        self.frame_4.setMaximumSize(QtCore.QSize(210, 235))
        self.frame_4.setStyleSheet("background-color: rgb(229, 255, 192);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.labeldistances_30 = QtWidgets.QLabel(self.frame_4)
        self.labeldistances_30.setGeometry(QtCore.QRect(30, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_30.setFont(font)
        self.labeldistances_30.setObjectName("labeldistances_30")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 40, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Checkbox_superadaptive = QtWidgets.QCheckBox(self.frame_4)
        self.Checkbox_superadaptive.setGeometry(QtCore.QRect(8, 80, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Checkbox_superadaptive.setFont(font)
        self.Checkbox_superadaptive.setObjectName("Checkbox_superadaptive")
        self.ButtonFullyAdaptive = QtWidgets.QRadioButton(self.frame_4)
        self.ButtonFullyAdaptive.setGeometry(QtCore.QRect(8, 124, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ButtonFullyAdaptive.setFont(font)
        self.ButtonFullyAdaptive.setObjectName("ButtonFullyAdaptive")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 105, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fresnelbutton = QtWidgets.QRadioButton(self.frame_4)
        self.fresnelbutton.setGeometry(QtCore.QRect(8, 60, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fresnelbutton.setFont(font)
        self.fresnelbutton.setChecked(True)
        self.fresnelbutton.setObjectName("fresnelbutton")
        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setGeometry(QtCore.QRect(6, 154, 196, 11))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.Loadbutton_User_def = QtWidgets.QPushButton(self.frame_4)
        self.Loadbutton_User_def.setGeometry(QtCore.QRect(10, 168, 68, 20))
        self.Loadbutton_User_def.setMinimumSize(QtCore.QSize(0, 20))
        self.Loadbutton_User_def.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Loadbutton_User_def.setFont(font)
        self.Loadbutton_User_def.setAutoFillBackground(False)
        self.Loadbutton_User_def.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.Loadbutton_User_def.setObjectName("Loadbutton_User_def")
        self.Label_user_def_dist = QtWidgets.QLabel(self.frame_4)
        self.Label_user_def_dist.setGeometry(QtCore.QRect(10, 195, 190, 10))
        self.Label_user_def_dist.setMinimumSize(QtCore.QSize(190, 0))
        self.Label_user_def_dist.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_user_def_dist.setFont(font)
        self.Label_user_def_dist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_user_def_dist.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Label_user_def_dist.setText("")
        self.Label_user_def_dist.setObjectName("Label_user_def_dist")
        self.User_defined_distr = QtWidgets.QRadioButton(self.frame_4)
        self.User_defined_distr.setGeometry(QtCore.QRect(10, 209, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.User_defined_distr.setFont(font)
        self.User_defined_distr.setChecked(False)
        self.User_defined_distr.setObjectName("User_defined_distr")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(83, 170, 122, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.frame_4, 0, 7, 1, 3)
        self.zoomButtonPeldorTT = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomButtonPeldorTT.sizePolicy().hasHeightForWidth())
        self.zoomButtonPeldorTT.setSizePolicy(sizePolicy)
        self.zoomButtonPeldorTT.setMinimumSize(QtCore.QSize(90, 16))
        self.zoomButtonPeldorTT.setMaximumSize(QtCore.QSize(90, 16))
        self.zoomButtonPeldorTT.setSizeIncrement(QtCore.QSize(23, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zoomButtonPeldorTT.setFont(font)
        self.zoomButtonPeldorTT.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.zoomButtonPeldorTT.setObjectName("zoomButtonPeldorTT")
        self.gridLayout.addWidget(self.zoomButtonPeldorTT, 1, 0, 1, 1)
        self.panPELDORTT = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panPELDORTT.sizePolicy().hasHeightForWidth())
        self.panPELDORTT.setSizePolicy(sizePolicy)
        self.panPELDORTT.setMinimumSize(QtCore.QSize(90, 16))
        self.panPELDORTT.setMaximumSize(QtCore.QSize(90, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.panPELDORTT.setFont(font)
        self.panPELDORTT.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.panPELDORTT.setObjectName("panPELDORTT")
        self.gridLayout.addWidget(self.panPELDORTT, 1, 1, 1, 1)
        self.DetachButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetachButton.sizePolicy().hasHeightForWidth())
        self.DetachButton.setSizePolicy(sizePolicy)
        self.DetachButton.setMinimumSize(QtCore.QSize(100, 16))
        self.DetachButton.setMaximumSize(QtCore.QSize(100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DetachButton.setFont(font)
        self.DetachButton.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.DetachButton.setObjectName("DetachButton")
        self.gridLayout.addWidget(self.DetachButton, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(230, 228))
        self.frame_2.setMaximumSize(QtCore.QSize(230, 300))
        self.frame_2.setStyleSheet("background-color: rgb(229, 255, 192);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.labeldistances_13 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_13.setGeometry(QtCore.QRect(80, 40, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_13.setFont(font)
        self.labeldistances_13.setObjectName("labeldistances_13")
        self.labeldistances_18 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_18.setGeometry(QtCore.QRect(178, 113, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_18.setFont(font)
        self.labeldistances_18.setObjectName("labeldistances_18")
        self.Moddepthedit = QtWidgets.QLineEdit(self.frame_2)
        self.Moddepthedit.setGeometry(QtCore.QRect(100, 62, 35, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Moddepthedit.setFont(font)
        self.Moddepthedit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Moddepthedit.setObjectName("Moddepthedit")
        self.Timescaleedit = QtWidgets.QLineEdit(self.frame_2)
        self.Timescaleedit.setGeometry(QtCore.QRect(10, 62, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Timescaleedit.setFont(font)
        self.Timescaleedit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Timescaleedit.setMaxLength(100000)
        self.Timescaleedit.setObjectName("Timescaleedit")
        self.labeldistances_17 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_17.setGeometry(QtCore.QRect(10, 177, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_17.setFont(font)
        self.labeldistances_17.setObjectName("labeldistances_17")
        self.labeldistances_9 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_9.setGeometry(QtCore.QRect(62, 64, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_9.setFont(font)
        self.labeldistances_9.setObjectName("labeldistances_9")
        self.labeldistances_10 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_10.setGeometry(QtCore.QRect(10, 40, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_10.setFont(font)
        self.labeldistances_10.setObjectName("labeldistances_10")
        self.Timescalebox = QtWidgets.QSpinBox(self.frame_2)
        self.Timescalebox.setEnabled(True)
        self.Timescalebox.setGeometry(QtCore.QRect(157, 62, 45, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Timescalebox.setFont(font)
        self.Timescalebox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Timescalebox.setReadOnly(False)
        self.Timescalebox.setMinimum(4)
        self.Timescalebox.setMaximum(128)
        self.Timescalebox.setSingleStep(4)
        self.Timescalebox.setProperty("value", 8)
        self.Timescalebox.setObjectName("Timescalebox")
        self.Sigmaedit = QtWidgets.QLineEdit(self.frame_2)
        self.Sigmaedit.setGeometry(QtCore.QRect(130, 110, 39, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Sigmaedit.setFont(font)
        self.Sigmaedit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Sigmaedit.setObjectName("Sigmaedit")
        self.EnableNoiseButton = QtWidgets.QRadioButton(self.frame_2)
        self.EnableNoiseButton.setGeometry(QtCore.QRect(100, 202, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.EnableNoiseButton.setFont(font)
        self.EnableNoiseButton.setCheckable(True)
        self.EnableNoiseButton.setChecked(False)
        self.EnableNoiseButton.setAutoExclusive(False)
        self.EnableNoiseButton.setObjectName("EnableNoiseButton")
        self.labeldistances_11 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_11.setGeometry(QtCore.QRect(50, 10, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_11.setFont(font)
        self.labeldistances_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labeldistances_11.setObjectName("labeldistances_11")
        self.labeldistances_12 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_12.setGeometry(QtCore.QRect(10, 111, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_12.setFont(font)
        self.labeldistances_12.setObjectName("labeldistances_12")
        self.labeldistances_8 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_8.setGeometry(QtCore.QRect(160, 40, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_8.setFont(font)
        self.labeldistances_8.setObjectName("labeldistances_8")
        self.SNR_edit = QtWidgets.QLineEdit(self.frame_2)
        self.SNR_edit.setGeometry(QtCore.QRect(10, 202, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SNR_edit.setFont(font)
        self.SNR_edit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.SNR_edit.setObjectName("SNR_edit")
        self.labeldistances_6 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_6.setGeometry(QtCore.QRect(208, 64, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_6.setFont(font)
        self.labeldistances_6.setObjectName("labeldistances_6")
        self.Universal_standard_dev_button = QtWidgets.QRadioButton(self.frame_2)
        self.Universal_standard_dev_button.setGeometry(QtCore.QRect(10, 140, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Universal_standard_dev_button.setFont(font)
        self.Universal_standard_dev_button.setCheckable(True)
        self.Universal_standard_dev_button.setChecked(False)
        self.Universal_standard_dev_button.setAutoExclusive(False)
        self.Universal_standard_dev_button.setObjectName("Universal_standard_dev_button")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(2, 90, 221, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(2, 160, 221, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.frame_2, 1, 4, 2, 3)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(210, 228))
        self.frame_3.setMaximumSize(QtCore.QSize(210, 300))
        self.frame_3.setStyleSheet("background-color: rgb(229, 255, 192);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.EnableBgButton = QtWidgets.QRadioButton(self.frame_3)
        self.EnableBgButton.setGeometry(QtCore.QRect(10, 190, 193, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.EnableBgButton.setFont(font)
        self.EnableBgButton.setCheckable(True)
        self.EnableBgButton.setChecked(True)
        self.EnableBgButton.setAutoExclusive(False)
        self.EnableBgButton.setObjectName("EnableBgButton")
        self.labeldistances_16 = QtWidgets.QLabel(self.frame_3)
        self.labeldistances_16.setGeometry(QtCore.QRect(8, 40, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_16.setFont(font)
        self.labeldistances_16.setObjectName("labeldistances_16")
        self.Bgdecayedit = QtWidgets.QLineEdit(self.frame_3)
        self.Bgdecayedit.setGeometry(QtCore.QRect(8, 60, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Bgdecayedit.setFont(font)
        self.Bgdecayedit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Bgdecayedit.setObjectName("Bgdecayedit")
        self.labeldistances_15 = QtWidgets.QLabel(self.frame_3)
        self.labeldistances_15.setGeometry(QtCore.QRect(40, 10, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_15.setFont(font)
        self.labeldistances_15.setObjectName("labeldistances_15")
        self.labeldistances_14 = QtWidgets.QLabel(self.frame_3)
        self.labeldistances_14.setGeometry(QtCore.QRect(10, 90, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_14.setFont(font)
        self.labeldistances_14.setObjectName("labeldistances_14")
        self.ShowBGButton = QtWidgets.QRadioButton(self.frame_3)
        self.ShowBGButton.setGeometry(QtCore.QRect(10, 160, 190, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ShowBGButton.setFont(font)
        self.ShowBGButton.setAutoExclusive(False)
        self.ShowBGButton.setObjectName("ShowBGButton")
        self.labeldistances_21 = QtWidgets.QLabel(self.frame_3)
        self.labeldistances_21.setGeometry(QtCore.QRect(63, 63, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_21.setFont(font)
        self.labeldistances_21.setObjectName("labeldistances_21")
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setGeometry(QtCore.QRect(8, 135, 196, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.BgDimbox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.BgDimbox.setGeometry(QtCore.QRect(10, 110, 57, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BgDimbox.setFont(font)
        self.BgDimbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BgDimbox.setDecimals(1)
        self.BgDimbox.setMinimum(1.0)
        self.BgDimbox.setMaximum(6.0)
        self.BgDimbox.setSingleStep(0.1)
        self.BgDimbox.setProperty("value", 3.0)
        self.BgDimbox.setObjectName("BgDimbox")
        self.gridLayout.addWidget(self.frame_3, 1, 7, 2, 3)
        self.FTwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FTwindow.sizePolicy().hasHeightForWidth())
        self.FTwindow.setSizePolicy(sizePolicy)
        self.FTwindow.setMinimumSize(QtCore.QSize(150, 230))
        self.FTwindow.setMaximumSize(QtCore.QSize(600, 600))
        self.FTwindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FTwindow.setObjectName("FTwindow")
        self.gridLayout.addWidget(self.FTwindow, 2, 0, 3, 2)
        self.Distancedistrwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Distancedistrwindow.sizePolicy().hasHeightForWidth())
        self.Distancedistrwindow.setSizePolicy(sizePolicy)
        self.Distancedistrwindow.setMinimumSize(QtCore.QSize(200, 230))
        self.Distancedistrwindow.setMaximumSize(QtCore.QSize(600, 600))
        self.Distancedistrwindow.setSizeIncrement(QtCore.QSize(0, 0))
        self.Distancedistrwindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Distancedistrwindow.setObjectName("Distancedistrwindow")
        self.gridLayout.addWidget(self.Distancedistrwindow, 2, 2, 3, 2)
        self.JarasprogressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.JarasprogressBar.setMinimumSize(QtCore.QSize(0, 23))
        self.JarasprogressBar.setMaximumSize(QtCore.QSize(16777215, 18))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.JarasprogressBar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.JarasprogressBar.setFont(font)
        self.JarasprogressBar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 0);\n"
"color: rgb(216, 255, 174);\n"
"background-color: rgb(255, 255, 255);")
        self.JarasprogressBar.setMaximum(100)
        self.JarasprogressBar.setProperty("value", 0)
        self.JarasprogressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.JarasprogressBar.setObjectName("JarasprogressBar")
        self.gridLayout.addWidget(self.JarasprogressBar, 3, 4, 1, 6)
        self.Startbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Startbutton.sizePolicy().hasHeightForWidth())
        self.Startbutton.setSizePolicy(sizePolicy)
        self.Startbutton.setMinimumSize(QtCore.QSize(120, 20))
        self.Startbutton.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Startbutton.setFont(font)
        self.Startbutton.setAutoFillBackground(False)
        self.Startbutton.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.Startbutton.setObjectName("Startbutton")
        self.gridLayout.addWidget(self.Startbutton, 4, 4, 1, 1)
        self.Savebutton = QtWidgets.QPushButton(self.centralwidget)
        self.Savebutton.setMinimumSize(QtCore.QSize(0, 20))
        self.Savebutton.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Savebutton.setFont(font)
        self.Savebutton.setAutoFillBackground(False)
        self.Savebutton.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.Savebutton.setObjectName("Savebutton")
        self.gridLayout.addWidget(self.Savebutton, 4, 5, 1, 1)
        self.Configurations = QtWidgets.QPushButton(self.centralwidget)
        self.Configurations.setMinimumSize(QtCore.QSize(0, 20))
        self.Configurations.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Configurations.setFont(font)
        self.Configurations.setAutoFillBackground(False)
        self.Configurations.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.Configurations.setObjectName("Configurations")
        self.gridLayout.addWidget(self.Configurations, 4, 6, 1, 2)
        self.Load_experimental_button = QtWidgets.QPushButton(self.centralwidget)
        self.Load_experimental_button.setMinimumSize(QtCore.QSize(0, 20))
        self.Load_experimental_button.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Load_experimental_button.setFont(font)
        self.Load_experimental_button.setAutoFillBackground(False)
        self.Load_experimental_button.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.Load_experimental_button.setObjectName("Load_experimental_button")
        self.gridLayout.addWidget(self.Load_experimental_button, 4, 8, 1, 1)
        self.Closebutton = QtWidgets.QPushButton(self.centralwidget)
        self.Closebutton.setMinimumSize(QtCore.QSize(0, 20))
        self.Closebutton.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Closebutton.setFont(font)
        self.Closebutton.setAutoFillBackground(False)
        self.Closebutton.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.Closebutton.setObjectName("Closebutton")
        self.gridLayout.addWidget(self.Closebutton, 4, 9, 1, 1)
        SimPel2018.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SimPel2018)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 25))
        self.menubar.setObjectName("menubar")
        SimPel2018.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SimPel2018)
        self.statusbar.setObjectName("statusbar")
        SimPel2018.setStatusBar(self.statusbar)

        self.retranslateUi(SimPel2018)
        QtCore.QMetaObject.connectSlotsByName(SimPel2018)

    def retranslateUi(self, SimPel2018):
        _translate = QtCore.QCoreApplication.translate
        SimPel2018.setWindowTitle(_translate("SimPel2018", "SimPel"))
        self.Coeff5edit.setText(_translate("SimPel2018", "0.0"))
        self.Coeff3edit.setText(_translate("SimPel2018", "0.0"))
        self.labeldistances_2.setText(_translate("SimPel2018", "nm"))
        self.labeldistances_19.setText(_translate("SimPel2018", "nm"))
        self.Distance4edit.setText(_translate("SimPel2018", "2.0"))
        self.Coeff2edit.setText(_translate("SimPel2018", "0.0"))
        self.labeldistances_29.setText(_translate("SimPel2018", "Distance Settings"))
        self.Distance3edit.setText(_translate("SimPel2018", "2.0"))
        self.Coeff4edit.setText(_translate("SimPel2018", "0.0"))
        self.labeldistances.setText(_translate("SimPel2018", "Distance"))
        self.labeldistances_4.setText(_translate("SimPel2018", "nm"))
        self.Distance5edit.setText(_translate("SimPel2018", "2.0"))
        self.Distance2edit.setText(_translate("SimPel2018", "2.0"))
        self.labeldistances_3.setText(_translate("SimPel2018", "nm"))
        self.labeldistances_5.setText(_translate("SimPel2018", "nm"))
        self.Coeff1edit.setText(_translate("SimPel2018", "1.0"))
        self.Distance1edit.setText(_translate("SimPel2018", "2.0"))
        self.labeldistances_7.setText(_translate("SimPel2018", "Coeff."))
        self.labeldistances_20.setText(_translate("SimPel2018", "Std. deviation"))
        self.Standard1.setText(_translate("SimPel2018", "0.1"))
        self.Standard2.setText(_translate("SimPel2018", "0.1"))
        self.Standard3.setText(_translate("SimPel2018", "0.1"))
        self.Standard4.setText(_translate("SimPel2018", "0.1"))
        self.Standard5.setText(_translate("SimPel2018", "0.1"))
        self.labeldistances_22.setText(_translate("SimPel2018", "nm"))
        self.labeldistances_23.setText(_translate("SimPel2018", "nm"))
        self.labeldistances_24.setText(_translate("SimPel2018", "nm"))
        self.labeldistances_25.setText(_translate("SimPel2018", "nm"))
        self.labeldistances_26.setText(_translate("SimPel2018", "nm"))
        self.labeldistances_30.setText(_translate("SimPel2018", "Integration Settings"))
        self.label.setText(_translate("SimPel2018", "Integrations methods"))
        self.Checkbox_superadaptive.setText(_translate("SimPel2018", "Higher discretization"))
        self.ButtonFullyAdaptive.setText(_translate("SimPel2018", "Fresnel+&very high discretization"))
        self.label_2.setText(_translate("SimPel2018", "High accuracy Integration "))
        self.fresnelbutton.setText(_translate("SimPel2018", "Fresnel ty&pe integration"))
        self.Loadbutton_User_def.setText(_translate("SimPel2018", "Load"))
        self.User_defined_distr.setText(_translate("SimPel2018", "Matri&x kernel  (user DD)"))
        self.label_3.setText(_translate("SimPel2018", "User defined distribution"))
        self.zoomButtonPeldorTT.setText(_translate("SimPel2018", "Zoom"))
        self.panPELDORTT.setText(_translate("SimPel2018", "Pan"))
        self.DetachButton.setText(_translate("SimPel2018", "Detach"))
        self.labeldistances_13.setText(_translate("SimPel2018", "Mod. depth"))
        self.labeldistances_18.setText(_translate("SimPel2018", "nm"))
        self.Moddepthedit.setText(_translate("SimPel2018", "0.2"))
        self.Timescaleedit.setText(_translate("SimPel2018", "1500"))
        self.labeldistances_17.setText(_translate("SimPel2018", "Signal-to-noise ratio"))
        self.labeldistances_9.setText(_translate("SimPel2018", "ns"))
        self.labeldistances_10.setText(_translate("SimPel2018", "Time scale"))
        self.Sigmaedit.setText(_translate("SimPel2018", "0.1"))
        self.EnableNoiseButton.setText(_translate("SimPel2018", "Enab&le noise"))
        self.labeldistances_11.setText(_translate("SimPel2018", "Simulation Options"))
        self.labeldistances_12.setText(_translate("SimPel2018", "Univ. standard dev."))
        self.labeldistances_8.setText(_translate("SimPel2018", "Step-size"))
        self.SNR_edit.setText(_translate("SimPel2018", "20.0"))
        self.labeldistances_6.setText(_translate("SimPel2018", "ns"))
        self.Universal_standard_dev_button.setText(_translate("SimPel2018", "&Universal standard deviaton"))
        self.EnableBgButton.setText(_translate("SimPel2018", "Enable background function "))
        self.labeldistances_16.setText(_translate("SimPel2018", "Background decay"))
        self.Bgdecayedit.setText(_translate("SimPel2018", "1.0"))
        self.labeldistances_15.setText(_translate("SimPel2018", "Background Signal"))
        self.labeldistances_14.setText(_translate("SimPel2018", "Background dimension"))
        self.ShowBGButton.setText(_translate("SimPel2018", "Show ba&ckground function"))
        self.labeldistances_21.setText(_translate("SimPel2018", "e-4  1/ns"))
        self.Startbutton.setText(_translate("SimPel2018", "Start"))
        self.Savebutton.setText(_translate("SimPel2018", "Save"))
        self.Configurations.setText(_translate("SimPel2018", "Config."))
        self.Load_experimental_button.setText(_translate("SimPel2018", "Load"))
        self.Closebutton.setText(_translate("SimPel2018", "Exit"))

